name: dart_amqp_client
description: Dart package that simplifies the handling of AMQP (Advanced Message Queuing Protocol) connections, channels, and associated callbacks. It provides an easy-to-use interface for establishing and managing connections to AMQP servers, enabling you to focus on your application's logic without dealing with low-level AMQP details.
version: 1.0.0
repository: https://github.com/Akhil-James/dart_amqp_client

topics: 
  - dart_amqp
  - AMQP
  - client
  - RabbitMQ

environment:
  sdk: ^3.1.4

dependencies:
 dart_amqp: ^0.2.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
