name: dart_amqp_client
description: Dart package that simplifies the handling of AMQP (Advanced Message Queuing Protocol) connections, channels, and associated callbacks.
version: 1.0.1
repository: https://github.com/Akhil-James/dart_amqp_client

topics: 
  - dart
  - amqp
  - client
  - rabbitmq

environment:
  sdk: ^3.1.4

dependencies:
 dart_amqp: ^0.2.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
